"""GET /v1/alerts — Alerts generated by the Rule Engine."""
from __future__ import annotations

import psycopg
from fastapi import APIRouter, Query

from app.core.config import settings

router = APIRouter()


@router.get('/alerts')
async def list_alerts(
    priority: str | None = Query(None, description='Filter: CRITICAL|HIGH'),
    limit: int = Query(30, ge=1, le=100),
    offset: int = Query(0, ge=0),
):
    try:
        url = settings.database_url.replace('+psycopg', '')
        with psycopg.connect(url) as conn:
            if priority:
                rows = conn.execute(
                    '''SELECT alert_id, story_id, priority, title, reason, triggered_at
                       FROM alerts WHERE priority = %s
                       ORDER BY triggered_at DESC LIMIT %s OFFSET %s''',
                    (priority.upper(), limit, offset),
                ).fetchall()
            else:
                rows = conn.execute(
                    '''SELECT alert_id, story_id, priority, title, reason, triggered_at
                       FROM alerts ORDER BY triggered_at DESC LIMIT %s OFFSET %s''',
                    (limit, offset),
                ).fetchall()
        alerts = [
            {
                'alert_id': str(r[0]), 'story_id': r[1], 'priority': r[2],
                'title': r[3], 'reason': r[4],
                'triggered_at': r[5].isoformat() if hasattr(r[5], 'isoformat') else str(r[5]),
            }
            for r in rows
        ]
        return {'alerts': alerts, 'count': len(alerts)}
    except Exception as exc:
        return {'alerts': [], 'count': 0, 'error': str(exc)}
