[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
loglevel=info

[program:nextjs]
command=node_modules/.bin/next start -p %(ENV_PORT)s
directory=/app/frontend
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nextjs.log
stderr_logfile=/var/log/supervisor/nextjs_err.log
environment=NODE_ENV="production"

[program:fastapi]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/fastapi.log
stderr_logfile=/var/log/supervisor/fastapi_err.log
